#!/usr/bin/env python3
"""
UTE Truth Merge Review Engine v1

Run from repository root:

    python 006-tools/truth-merge/truth-merge-review-engine-v1.py

Purpose:
    Detect duplicate or near-duplicate truth concepts in the current UTE truth index.

This tool does not delete, merge, or supersede truths.
It produces a review report only.

Reads:
    003-machine-readable/truth-index-v1.json

Writes:
    003-machine-readable/truth-merge-review-report-v1.json
    003-machine-readable/truth-merge-review-report-v1.md
    docs/data/truth-merge-review-report-v1.json
"""

from pathlib import Path
import json
from datetime import datetime, timezone
from difflib import SequenceMatcher

ROOT = Path.cwd()
MACHINE = ROOT / "003-machine-readable"
DOCS_DATA = ROOT / "docs" / "data"

INDEX_PATH = MACHINE / "truth-index-v1.json"

OUT_JSON_INTERNAL = MACHINE / "truth-merge-review-report-v1.json"
OUT_MD_INTERNAL = MACHINE / "truth-merge-review-report-v1.md"
OUT_JSON_PUBLIC = DOCS_DATA / "truth-merge-review-report-v1.json"

def read_json(path):
    return json.loads(path.read_text(encoding="utf-8"))

def norm(text):
    return (text or "").strip().lower().replace("/", " ").replace("-", " ")

def similarity(a, b):
    return SequenceMatcher(None, norm(a), norm(b)).ratio()

def recommendation_for(pair):
    if pair["title_similarity"] >= 0.98:
        return "merge_or_supersede_review"
    if pair["title_similarity"] >= 0.86:
        return "near_duplicate_review"
    return "retain_pending_context_review"

def main():
    if not INDEX_PATH.exists():
        raise SystemExit("ERROR: truth-index-v1.json not found. Run topology generator first.")

    index = read_json(INDEX_PATH)
    truths = index.get("truths", [])

    exact_title_groups = {}
    for truth in truths:
        title_key = norm(truth.get("title", ""))
        if title_key:
            exact_title_groups.setdefault(title_key, []).append(truth)

    exact_duplicates = []
    for title_key, items in exact_title_groups.items():
        if len(items) > 1:
            exact_duplicates.append({
                "title_key": title_key,
                "entries": [
                    {
                        "id": item.get("id"),
                        "title": item.get("title"),
                        "domain": item.get("domain"),
                        "statement": item.get("statement"),
                        "dependencies": item.get("dependencies", [])
                    }
                    for item in items
                ],
                "recommended_action": "select_authoritative_entry_and_mark_others_as_alias_or_superseded"
            })

    near_duplicates = []
    for i, a in enumerate(truths):
        for b in truths[i+1:]:
            a_title = a.get("title", "")
            b_title = b.get("title", "")
            if not a_title or not b_title:
                continue

            sim = similarity(a_title, b_title)
            if sim >= 0.86 and norm(a_title) != norm(b_title):
                pair = {
                    "a": {
                        "id": a.get("id"),
                        "title": a_title,
                        "domain": a.get("domain")
                    },
                    "b": {
                        "id": b.get("id"),
                        "title": b_title,
                        "domain": b.get("domain")
                    },
                    "title_similarity": round(sim, 3)
                }
                pair["recommended_action"] = recommendation_for(pair)
                near_duplicates.append(pair)

    report = {
        "report_id": "UTE-TRUTH-MERGE-REVIEW-REPORT-V1",
        "generated_by": "UTE Truth Merge Review Engine v1",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "truth_count": len(truths),
        "exact_duplicate_group_count": len(exact_duplicates),
        "near_duplicate_pair_count": len(near_duplicates),
        "exact_duplicates": exact_duplicates,
        "near_duplicates": sorted(near_duplicates, key=lambda p: p["title_similarity"], reverse=True),
        "governance_rule": "Merge review reports are advisory. No truth may be merged, deleted, or superseded without explicit review."
    }

    MACHINE.mkdir(parents=True, exist_ok=True)
    DOCS_DATA.mkdir(parents=True, exist_ok=True)

    json_text = json.dumps(report, indent=2, ensure_ascii=False) + "\n"
    OUT_JSON_INTERNAL.write_text(json_text, encoding="utf-8")
    OUT_JSON_PUBLIC.write_text(json_text, encoding="utf-8")

    md = [
        "# UTE Truth Merge Review Report v1",
        "",
        f"Generated by: {report['generated_by']}",
        f"Truth count: {report['truth_count']}",
        f"Exact duplicate groups: {report['exact_duplicate_group_count']}",
        f"Near duplicate pairs: {report['near_duplicate_pair_count']}",
        "",
        "This report is advisory only. It does not merge or delete truths.",
        "",
        "## Exact Duplicate Groups",
        ""
    ]

    if not exact_duplicates:
        md.append("No exact duplicate title groups detected.")
        md.append("")

    for group in exact_duplicates:
        md.extend([
            f"### {group['title_key']}",
            "",
            f"Recommended action: `{group['recommended_action']}`",
            ""
        ])
        for entry in group["entries"]:
            md.extend([
                f"- `{entry['id']}` — {entry['title']} ({entry.get('domain')})",
                f"  - Statement: {entry.get('statement') or '[blank]'}"
            ])
        md.append("")

    md.extend([
        "## Near Duplicate Pairs",
        ""
    ])

    if not near_duplicates:
        md.append("No near duplicate title pairs detected.")
        md.append("")

    for pair in sorted(near_duplicates, key=lambda p: p["title_similarity"], reverse=True):
        md.extend([
            f"### {pair['a']['title']} / {pair['b']['title']}",
            "",
            f"Similarity: `{pair['title_similarity']}`",
            f"Recommended action: `{pair['recommended_action']}`",
            f"- `{pair['a']['id']}` — {pair['a']['title']} ({pair['a'].get('domain')})",
            f"- `{pair['b']['id']}` — {pair['b']['title']} ({pair['b'].get('domain')})",
            ""
        ])

    OUT_MD_INTERNAL.write_text("\n".join(md), encoding="utf-8")

    print("UTE Truth Merge Review Engine v1 complete.")
    print("Truths:", len(truths))
    print("Exact duplicate groups:", len(exact_duplicates))
    print("Near duplicate pairs:", len(near_duplicates))
    for group in exact_duplicates:
        ids = ", ".join(entry["id"] for entry in group["entries"])
        print("- exact:", group["title_key"], ids)
    print("Wrote:", OUT_JSON_INTERNAL)
    print("Wrote:", OUT_MD_INTERNAL)
    print("Wrote:", OUT_JSON_PUBLIC)

if __name__ == "__main__":
    main()
